from PyQt4 import QtCore, QtGui
from kdatewidget import KDateWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 40, 271, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 20, 131, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 40, 241, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 161, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 40, 241, 27))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.kdatewidget = KDateWidget(self.centralwidget)
        self.kdatewidget.setGeometry(QtCore.QRect(40, 90, 248, 27))
        self.kdatewidget.setObjectName(_fromUtf8("kdatewidget"))
        self.kdatewidget_2 = KDateWidget(self.centralwidget)
        self.kdatewidget_2.setGeometry(QtCore.QRect(330, 90, 248, 27))
        self.kdatewidget_2.setObjectName(_fromUtf8("kdatewidget_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 68, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 100, 68, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 90, 201, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 140, 771, 361))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(770, 140, 16, 361))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 520, 99, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 520, 99, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 520, 99, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivio_Supplenze = QtGui.QMenu(self.menubar)
        self.menuArchivio_Supplenze.setObjectName(_fromUtf8("menuArchivio_Supplenze"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAiuto = QtGui.QAction(MainWindow)
        self.actionAiuto.setObjectName(_fromUtf8("actionAiuto"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionVersione_1_0 = QtGui.QAction(MainWindow)
        self.actionVersione_1_0.setObjectName(_fromUtf8("actionVersione_1_0"))
        self.menuArchivio_Supplenze.addAction(self.actionAiuto)
        self.menuArchivio_Supplenze.addAction(self.actionInfo)
        self.menuArchivio_Supplenze.addSeparator()
        self.menuArchivio_Supplenze.addAction(self.actionVersione_1_0)
        self.menubar.addAction(self.menuArchivio_Supplenze.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Archivio Supplenze", None))
        self.label.setText(_translate("MainWindow", "Istituto comprensivo:", None))
        self.label_2.setText(_translate("MainWindow", "Classe di concorso:", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Infanzia", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Primaria", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Secondaria 1° grado", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Secondaria 2° grado", None))
        self.label_3.setText(_translate("MainWindow", "Tipologia di impiego:", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Docente comune", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Docente di sostegno", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Educatore", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "ATA", None))
        self.label_4.setText(_translate("MainWindow", "Dal:", None))
        self.label_5.setText(_translate("MainWindow", "Al:", None))
        self.pushButton.setText(_translate("MainWindow", "Aggiungi supplenza", None))
        self.pushButton_2.setText(_translate("MainWindow", "Backup", None))
        self.pushButton_3.setText(_translate("MainWindow", "Modifica", None))
        self.pushButton_4.setText(_translate("MainWindow", "Chiudi", None))
        self.menuArchivio_Supplenze.setTitle(_translate("MainWindow", "Archivio Supplenze", None))
        self.actionAiuto.setText(_translate("MainWindow", "Aiuto", None))
        self.actionInfo.setText(_translate("MainWindow", "Info", None))
        self.actionVersione_1_0.setText(_translate("MainWindow", "Versione 1.0", None))

